### PR TITLE
fix: Commands wont be suggested due to client-sided NPE

### LINKED ISSUE #22: Command suggestions gone
After installing this mod i no longer get command suggestions. The commands are still working, but the suggestions are not showing.

I run a dedicated pc just for the server and the client on another pc.
Before installing a mod i take a backup, and just by stopping the server with this mod and starting the backup (saved just before i installed the mod) i was able to get the suggestions again. So clearly this mod does something. (The client was left running in between server change)

Both server and client run on  Forge 1.20.2-48.1.0
Tested mod version:   svmm-1.20.1-1.2.4.0
I also have a few other mods but everything worked fine before.

### PR DESCRIPTION
**Pull request by hamusuke0323**
This PR fixes #22.
An EnumArgument is instantiated with ConfigKeys enum class, but clients do not have that class, you know.
Because of this, a NullPointerException occurs in client-side.

### CODE REVIEW

**Review by Tourmi — CHANGES_REQUESTED** [review]
I was never able to reproduce this bug on my end, so I appreciate the PR a ton!

I assume you've been able to reproduce the original bug, what were the mods installed on the server and on the client? Need to reproduce this on my end to make sure #22 can be closed

**Comment by hamusuke0323** [comment]
> I was never able to reproduce this bug on my end, so I appreciate the PR a ton!
> 
> I assume you've been able to reproduce the original bug, what were the mods installed on the server and on the client? Need to reproduce this on my end to make sure #22 can be closed

Server: this mod only

Client: None

**Comment by Tourmi** [comment]
Does the client run Forge, just without any mods? I think I only tested vanilla clients on modded servers previously

**Comment by hamusuke0323** [comment]
> Does the client run Forge, just without any mods? I think I only tested vanilla clients on modded servers previously

image

This is a client-sided log. I joined the server, then NullPointerException occurs. Thanks to this log, I could fix the bug.

**Review by Tourmi — APPROVED** [review]

**Comment by Tourmi** [comment]
Tested with a Forge client that had no mods and a modded server, I was able to reproduce the issue, and your PR indeed fixes it! Thanks!

**Pull request merged**
